name: Build_With_Stable_2x

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]

jobs:
  windows:    
    name: build on windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build with dotnet
      run: dotnet build --configuration Release --source https://api.nuget.org/v3/index.json
      
  linux:    
    name: build on linux
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Show dotnet Version
      run: dotnet --version
    - name: Show java Version
      run: java -version  
    - name: Setup Stable 2.x Nacos Server
      run: |      
        wget https://github.com/alibaba/nacos/releases/download/2.0.0-bugfix/nacos-server-2.0.0.tar.gz
        tar -xvf nacos-server-2.0.0.tar.gz
        cd nacos/bin
        # sed -i 's/nacos.core.auth.enabled=false/nacos.core.auth.enabled=true/g' ../conf/application.properties
        chmod 755 startup.sh
        nohup ./startup.sh -m standalone 2>&1 &
        sleep 30
        curl "127.0.0.1:8848/nacos/v1/ns/operator/metrics"   
    - name: Build with dotnet
      run: dotnet build --configuration Release 
    - name: Test with dotnet
      run: dotnet test --filter "Category=all|Category=1x|Category=2x"
    - name: Upload Nacos logs
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: nacos-logs
        path: /home/runner/work/nacos-sdk-csharp/nacos-sdk-csharp/nacos/logs
